// <auto-generated />
namespace InventarioPizzeriaDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class junio6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(junio6));
        
        string IMigrationMetadata.Id
        {
            get { return "201806070053175_junio6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
